apiVersion: apps/v1
kind: Deployment
metadata: 
  name: argo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ngx 
  template:
    spec:
       containers: 
         - name: argoapp
           image: nginx
           ports:
             - containerPort: 80
    metadata:
      labels:
        app: ngx
